# students.py
STUDENTS = [
    {"name": "Faysal (1)", "roll": "03", "id": "BQSHK01", "department": "Khatmi / Recitation"},
    {"name": "Sown", "roll": "04", "id": "BQSHK02", "department": "Khatmi / Recitation"},
    {"name": "Abu Talha", "roll": "05", "id": "BQSHK03", "department": "Khatmi / Recitation"},
    {"name": "Abdullah Al Mahi", "roll": "06", "id": "BQSHK04", "department": "Khatmi / Recitation"},
    {"name": "Faysal (2)", "roll": "07", "id": "BQSHK05", "department": "Khatmi / Recitation"},
    {"name": "Jarif", "roll": "08", "id": "BQSHK06", "department": "Khatmi / Recitation"},
    {"name": "Asif", "roll": "09", "id": "BQSHK07", "department": "Khatmi / Recitation"},
    {"name": "Jihad", "roll": "10", "id": "BQSHK08", "department": "Khatmi / Recitation"},
    {"name": "Sakib", "roll": "11", "id": "BQSHK09", "department": "Khatmi / Recitation"},
    {"name": "Tawfiq", "roll": "12", "id": "BQSHK10", "department": "Khatmi / Recitation"},
    {"name": "Mosaddek", "roll": "31", "id": "BQSHK11", "department": "Khatmi / Recitation"},
    {"name": "Jubayer", "roll": "01", "id": "BQSHS01", "department": "Hifz 1–29"},
    {"name": "Anamul Haqe", "roll": "02", "id": "BQSHS18", "department": "Hifz 1–29"},
    {"name": "Mafin", "roll": "13", "id": "BQSHS11", "department": "Hifz 1–29"},
    {"name": "Hasib", "roll": "14", "id": "BQSHS12", "department": "Hifz 1–29"},
    {"name": "Sahadat", "roll": "15", "id": "BQSHS13", "department": "Hifz 1–29"},
    {"name": "Arafat (1)", "roll": "16", "id": "BQSHS19", "department": "Hifz 1–29"},
    {"name": "Sabbir", "roll": "17", "id": "BQSHS02", "department": "Hifz 1–29"},
    {"name": "Hujayfa", "roll": "18", "id": "BQSHS14", "department": "Hifz 1–29"},
    {"name": "Afrad", "roll": "19", "id": "BQSHS03", "department": "Hifz 1–29"},
    {"name": "Rahat", "roll": "20", "id": "BQSHS04", "department": "Hifz 1–29"},
    {"name": "Abid", "roll": "21", "id": "BQSHS05", "department": "Hifz 1–29"},
    {"name": "Arafat (2)", "roll": "22", "id": "BQSHS06", "department": "Hifz 1–29"},
    {"name": "Al‑Amin", "roll": "25", "id": "BQSHS15", "department": "Hifz 1–29"},
    {"name": "Sayem", "roll": "26", "id": "BQSHS20", "department": "Hifz 1–29"},
    {"name": "Tahmid", "roll": "27", "id": "BQSHS21", "department": "Hifz 1–29"},
    {"name": "Akib", "roll": "28", "id": "BQSHS07", "department": "Hifz 1–29"},
    {"name": "Amir Hamja", "roll": "29", "id": "BQSHS08", "department": "Hifz 1–29"},
    {"name": "Nabil", "roll": "30", "id": "BQSHS09", "department": "Hifz 1–29"},
    {"name": "Junayed", "roll": "33", "id": "BQSHS10", "department": "Hifz 1–29"},
    {"name": "Shoyab", "roll": "34", "id": "BQSHS16", "department": "Hifz 1–29"},
    {"name": "Junayed", "roll": "35", "id": "BQSHS17", "department": "Hifz 1–29"},
    {"name": "Abu Talha", "roll": "01", "id": "BQSNA01", "department": "Pre-Hifz Nazara"},
    {"name": "Kawser Ahmad", "roll": "02", "id": "BQSNA02", "department": "Pre-Hifz Nazara"},
    {"name": "Sifat", "roll": "03", "id": "BQSNA03", "department": "Pre-Hifz Nazara"},
    {"name": "Shahinur", "roll": "04", "id": "BQSNA04", "department": "Pre-Hifz Nazara"},
    {"name": "Miraj", "roll": "05", "id": "BQSNA05", "department": "Pre-Hifz Nazara"},
    {"name": "Minhaz", "roll": "06", "id": "BQSNA06", "department": "Pre-Hifz Nazara"},
    {"name": "Lijon", "roll": "07", "id": "BQSNA07", "department": "Pre-Hifz Nazara"},
    {"name": "Rafan", "roll": "08", "id": "BQSNA08", "department": "Pre-Hifz Nazara"},
    {"name": "Arshad", "roll": "09", "id": "BQSNA09", "department": "Pre-Hifz Nazara"},
    {"name": "Jidan", "roll": "01", "id": "BQSNU01", "department": "Nurani Maktab"},
    {"name": "Safan", "roll": "02", "id": "BQSNU02", "department": "Nurani Maktab"},
    {"name": "Moballig", "roll": "03", "id": "BQSNU03", "department": "Nurani Maktab"},
    {"name": "Shoyaib", "roll": "04", "id": "BQSNU04", "department": "Nurani Maktab"},
    {"name": "Sajjad", "roll": "05", "id": "BQSNU05", "department": "Nurani Maktab"},
    {"name": "Tamim", "roll": "06", "id": "BQSNU06", "department": "Nurani Maktab"},
    {"name": "Ruman", "roll": "07", "id": "BQSNU07", "department": "Nurani Maktab"},
    {"name": "Mahdi", "roll": "08", "id": "BQSNU08", "department": "Nurani Maktab"},
    {"name": "Soyad", "roll": "09", "id": "BQSNU09", "department": "Nurani Maktab"},
]

TEACHERS = [
    {"name": "Ustad Arif", "phone": "01824401812"},
    {"name": "Ustad Arif Robbani", "phone": "01631-940605"},
    {"name": "Ustad Jafor", "phone": "01892051303"},
]
